"""Generate data/nutrition_db.json for all 25 classes.

Values are hand-authored averages based on USDA FoodData Central entries for
typical restaurant preparations. Azerbaijani names and notes are reviewed by a
native speaker (STOP 3). Sources cited in README.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]

from config import CLASSES, settings  # noqa: E402


def entry(az_name: str, kcal: float, protein: float, carb: float, fat: float,
          fiber: float, sugar: float, sodium: int, serving_g: int,
          serving_az: str, density: float, tags: list[str], notes_az: str) -> dict:
    """Build one nutrition_db entry in the spec 3.2 schema."""
    return {
        "az_name": az_name,
        "per_100g": {"kcal": kcal, "protein_g": protein, "carb_g": carb,
                     "fat_g": fat, "fiber_g": fiber, "sugar_g": sugar,
                     "sodium_mg": sodium},
        "typical_serving_g": serving_g,
        "serving_name_az": serving_az,
        "density_g_per_cm2": density,
        "tags": tags,
        "notes_az": notes_az,
    }


DB: dict[str, dict] = {
    "pizza": entry("Pitsa", 266, 11.0, 33.0, 10.0, 2.3, 3.6, 598, 107, "dilim", 1.1,
                   ["fast_food", "high_sodium", "high_carb"],
                   "Yüksək natrium və doymuş yağ var. Nazik xəmirli və tərəvəzli variant daha yaxşı seçimdir."),
    "hamburger": entry("Hamburger", 254, 13.0, 24.0, 12.0, 1.5, 5.0, 414, 226, "ədəd", 1.5,
                       ["fast_food", "high_fat", "high_sodium"],
                       "Kalori sıxlığı yüksəkdir. Sousu azaldıb salat əlavə etsəniz, daha balanslı olar."),
    "french_fries": entry("Kartof fri", 312, 3.4, 41.0, 15.0, 3.8, 0.3, 210, 117, "porsiya", 0.9,
                          ["fast_food", "high_fat", "high_carb"],
                          "Dərin yağda qızardılır və kalorisi yüksəkdir. Sobada bişmiş kartof daha sağlam alternativdir."),
    "caesar_salad": entry("Sezar salatı", 190, 8.0, 8.0, 14.0, 1.8, 2.0, 380, 220, "boşqab", 0.5,
                          ["high_fat", "high_sodium"],
                          "Kalorinin çoxu sousdan gəlir. Sousu ayrıca istəyib az istifadə etmək olar."),
    "sushi": entry("Suşi", 150, 6.0, 28.0, 1.5, 0.9, 3.0, 335, 200, "porsiya", 0.8,
                   ["high_carb", "high_sodium"],
                   "Yağı azdır, amma soya sousu natriumu xeyli artırır. Sousu az işlədin."),
    "steak": entry("Mal əti steyki", 271, 26.0, 0.0, 18.0, 0.0, 0.0, 58, 220, "porsiya", 1.3,
                   ["high_protein", "high_fat"],
                   "Zülalla zəngindir. Yağsız hissələri seçib tərəvəzlə birlikdə yemək məsləhətdir."),
    "fried_rice": entry("Qızardılmış düyü", 163, 4.5, 28.0, 4.0, 0.9, 1.0, 396, 198, "boşqab", 0.9,
                        ["high_carb", "high_sodium"],
                        "Adi düyüdən daha yağlı və duzludur. Tərəvəz və zülal əlavə etsəniz, daha doyumlu olar."),
    "spaghetti_bolognese": entry("Bolonez spagetti", 129, 7.0, 15.0, 4.5, 1.5, 2.5, 240, 300, "boşqab", 0.9,
                                 ["high_carb"],
                                 "Balanslı yeməkdir, amma porsiya ölçüsünə fikir verin. Tam taxıl makaron daha çox lif verir."),
    "pancakes": entry("Pankek", 227, 6.0, 28.0, 10.0, 1.2, 8.0, 430, 116, "ədəd", 0.8,
                      ["high_carb", "high_sugar"],
                      "Sirop və kərə yağı ilə kalorisi sürətlə artır. Meyvə ilə yemək daha yaxşı seçimdir."),
    "omelette": entry("Omlet", 154, 11.0, 1.0, 12.0, 0.0, 0.5, 155, 122, "porsiya", 0.9,
                      ["high_protein"],
                      "Zülalla zəngin səhər yeməyidir. Tərəvəz əlavə etsəniz, vitamin dəyəri artar."),
    "grilled_salmon": entry("Qril qızılbalıq", 208, 22.0, 0.0, 13.0, 0.0, 0.0, 59, 170, "porsiya", 1.0,
                            ["high_protein", "healthy_fat"],
                            "Omeqa-3 yağ turşuları ilə zəngindir. Həftədə 2 dəfə balıq yemək ürək sağlamlığına xeyirlidir."),
    "chicken_curry": entry("Toyuq kari", 120, 12.0, 6.0, 5.5, 1.0, 2.0, 350, 235, "porsiya", 0.9,
                           ["high_protein"],
                           "Zülal mənbəyidir. Kremli variantlar daha kalorili olur, pomidor əsaslı sous daha yüngüldür."),
    "donuts": entry("Ponçik", 421, 5.0, 50.0, 23.0, 1.5, 23.0, 373, 60, "ədəd", 0.7,
                    ["high_sugar", "high_fat", "fast_food"],
                    "Şəkər və yağ nisbəti çox yüksəkdir. Gündəlik yox, arabir yemək məsləhətdir."),
    "cheesecake": entry("Çizkeyk", 321, 5.5, 26.0, 23.0, 0.4, 22.0, 438, 125, "dilim", 1.0,
                        ["high_sugar", "high_fat"],
                        "Kalorili desertdir. Kiçik dilimlə kifayətlənmək və şəkərli içki ilə yeməmək daha yaxşıdır."),
    "ice_cream": entry("Dondurma", 207, 3.5, 24.0, 11.0, 0.7, 21.0, 80, 66, "kürəcik", 0.7,
                       ["high_sugar"],
                       "1 kürəcik ağlabatan porsiyadır. Meyvəli sorbet daha az kalorili alternativdir."),
    "hot_dog": entry("Hot-doq", 290, 10.0, 24.0, 17.0, 0.9, 4.0, 810, 150, "ədəd", 1.0,
                     ["fast_food", "high_sodium"],
                     "Natrium miqdarı çox yüksəkdir. Emal olunmuş ət məhsullarını tez-tez yemək məsləhət deyil."),
    "dumplings": entry("Düşbərə (dumplinq)", 190, 8.0, 25.0, 6.0, 1.2, 1.0, 420, 180, "porsiya", 0.9,
                       ["high_carb"],
                       "Buxarda bişmiş variant qızardılmışdan daha yüngüldür. Sirkə və istiotla dadlandırmaq olar."),
    "falafel": entry("Falafel", 333, 13.0, 32.0, 18.0, 4.9, 1.0, 294, 102, "porsiya", 0.8,
                     ["vegetarian", "high_fiber", "high_fat"],
                     "Bitki mənşəli zülal və lif mənbəyidir. Dərin yağda qızardıldığı üçün kalorisi yüksəkdir."),
    "greek_salad": entry("Yunan salatı", 105, 2.5, 6.0, 8.0, 1.9, 4.0, 310, 250, "boşqab", 0.5,
                         ["healthy_fat"],
                         "Zeytun yağı və tərəvəzlərlə yüngül seçimdir. Pendirin miqdarı duz balansına təsir edir."),
    "lasagna": entry("Lazanya", 155, 9.0, 14.0, 7.0, 1.3, 3.5, 340, 250, "dilim", 1.1,
                     ["high_carb", "high_sodium"],
                     "Doyurucu yeməkdir, amma porsiyanı böyütməyin. Yanında yaşıl salat yaxşı gedir."),
    "ramen": entry("Ramen şorbası", 89, 4.0, 12.0, 3.0, 0.8, 1.0, 450, 500, "kasa", 0.6,
                   ["high_sodium"],
                   "Bulyonun duzu çox olur. Bulyonu tam içməsəniz, natrium qəbulunuz xeyli azalar."),
    "waffles": entry("Vafli", 291, 7.9, 37.0, 13.0, 1.7, 10.0, 511, 75, "ədəd", 0.8,
                     ["high_carb", "high_sugar"],
                     "Sirop əlavə etməzdən əvvəl kalorini nəzərə alın. Meyvə və qatıqla daha balanslı olur."),
    "tacos": entry("Tako", 216, 12.0, 20.0, 10.0, 2.5, 2.0, 397, 170, "ədəd", 0.9,
                   ["fast_food", "high_sodium"],
                   "Tərkib seçimi kalorini müəyyən edir. Qızardılmış yox, qril ət və bol tərəvəz seçin."),
    "guacamole": entry("Quakamole", 157, 2.0, 8.5, 14.0, 6.7, 0.7, 315, 100, "porsiya", 0.7,
                       ["healthy_fat", "high_fiber"],
                       "Avokadonun faydalı yağları ilə zəngindir. Çips əvəzinə tərəvəz çubuqları ilə yeyin."),
    "club_sandwich": entry("Klub sendviç", 240, 14.0, 25.0, 9.5, 1.6, 4.0, 560, 230, "ədəd", 0.9,
                           ["high_sodium"],
                           "Mayonez və bekon kalorini artırır. Tam taxıl çörəklə və az sousla daha yaxşı olar."),
    "apple_pie": entry("Alma piroqu", 237, 2.4, 34.0, 11.0, 1.6, 16.0, 266, 125, "dilim", 0.9,
                       ["high_sugar", "high_carb"],
                       "Şəkər və xəmirdən kalorisi yüksəkdir. Kiçik dilim və şəkərsiz çay ilə balanslaşdırın."),
    "baby_back_ribs": entry("Donuz qabırğası (barbekü)", 292, 24.0, 8.0, 18.0, 0.3, 6.0, 560, 250, "porsiya", 1.2,
                            ["high_protein", "high_fat", "high_sodium"],
                            "Sous natriumu və şəkəri artırır. Yağsız hissələri seçib tərəvəzlə yeyin."),
    "baklava": entry("Paxlava", 428, 6.0, 45.0, 26.0, 2.5, 30.0, 220, 80, "ədəd", 1.0,
                     ["high_sugar", "high_fat"],
                     "Şərbət və qoz-fındıqla çox kaloridir. Bayram üçün arabir, kiçik porsiya seçin."),
    "beef_carpaccio": entry("Mal əti karpaççosu", 190, 20.0, 1.0, 12.0, 0.2, 0.3, 380, 120, "porsiya", 0.9,
                            ["high_protein"],
                            "Zülalla zəngindir. Nazik dilimlənmiş çiy ət olduğu üçün təzəliyinə diqqət edin."),
    "beef_tartare": entry("Mal əti tartarı", 196, 19.0, 2.0, 12.0, 0.3, 0.5, 350, 150, "porsiya", 0.9,
                          ["high_protein"],
                          "Çiy ət yeməyidir; keyfiyyət və gigiyena vacibdir. Zülal mənbəyidir."),
    "beet_salad": entry("Çuğundur salatı", 90, 2.0, 12.0, 4.0, 2.8, 8.0, 250, 200, "boşqab", 0.6,
                        ["healthy_fat", "high_fiber"],
                        "Lif və antioksidantlarla zəngin yüngül seçimdir. Şəkəri təbii çuğundurdan gəlir."),
    "beignets": entry("Benye (şirin xəmir)", 380, 6.0, 45.0, 19.0, 1.5, 15.0, 300, 70, "ədəd", 0.6,
                      ["high_sugar", "high_fat"],
                      "Dərin yağda qızardılıб pudra şəkəri ilə verilir. Arabir yemək daha yaxşıdır."),
    "bibimbap": entry("Bibimbap", 130, 6.0, 18.0, 4.0, 2.0, 3.0, 400, 400, "kasa", 0.8,
                      ["high_carb"],
                      "Düyü, tərəvəz və zülalla balanslı Koreya yeməyidir. Sousu az qatsanız, duz azalar."),
    "bread_pudding": entry("Çörək pudinqi", 250, 5.0, 35.0, 10.0, 1.0, 20.0, 260, 150, "porsiya", 0.9,
                           ["high_sugar", "high_carb"],
                           "Şəkər və çörəkdən kalorisi yüksəkdir. Meyvə əlavəsi ilə lif dəyərini artırın."),
    "breakfast_burrito": entry("Səhər burritosu", 210, 9.0, 20.0, 11.0, 1.8, 1.5, 480, 220, "ədəd", 1.0,
                               ["high_sodium"],
                               "Yumurta və tərəvəzlə doyumlu səhər yeməyidir. Emal olunmuş ət natriumu artırır."),
    "bruschetta": entry("Brusketta", 200, 5.0, 25.0, 9.0, 1.8, 2.5, 380, 120, "porsiya", 0.6,
                        ["high_carb"],
                        "Zeytun yağı və pomidorla yüngül başlanğıcdır. Çörək miqdarı kalorini müəyyən edir."),
    "cannoli": entry("Kannoli", 350, 6.0, 40.0, 18.0, 1.0, 25.0, 180, 90, "ədəd", 0.9,
                     ["high_sugar", "high_fat"],
                     "Şirin rikotta doldurması ilə kaloridir. Kiçik ölçü seçib şəkərə diqqət edin."),
    "caprese_salad": entry("Kapreze salatı", 150, 8.0, 4.0, 11.0, 0.8, 3.0, 280, 200, "boşqab", 0.6,
                           ["healthy_fat"],
                           "Mozzarella, pomidor və reyhanla yüngül seçimdir. Zeytun yağını ölçülü işlədin."),
    "carrot_cake": entry("Yerkökü tortu", 340, 4.0, 45.0, 16.0, 1.5, 32.0, 300, 110, "dilim", 0.9,
                         ["high_sugar", "high_fat"],
                         "Yerkökünə baxmayaraq şəkər və krem yüksəkdir. Kiçik dilimlə kifayətlənin."),
    "ceviche": entry("Seviçe (marinadlanmış balıq)", 110, 18.0, 4.0, 2.0, 0.5, 1.5, 350, 180, "porsiya", 0.8,
                     ["high_protein"],
                     "Sitrusla marinadlanmış yüngül, zülallı balıq yeməyidir. Yağı azdır."),
    "cheese_plate": entry("Pendir boşqabı", 370, 22.0, 3.0, 30.0, 0.0, 1.0, 620, 120, "porsiya", 1.0,
                          ["high_fat", "high_sodium", "high_protein"],
                          "Doymuş yağ və natrium yüksəkdir. Kiçik porsiya və meyvə ilə balanslaşdırın."),
    "chicken_quesadilla": entry("Toyuqlu kesadiya", 260, 15.0, 22.0, 13.0, 1.5, 2.0, 520, 200, "porsiya", 1.0,
                                ["high_sodium"],
                                "Pendir və tortilyadan yağlıdır. Bol tərəvəz və az pendir daha balanslıdır."),
    "chicken_wings": entry("Toyuq qanadı", 290, 26.0, 2.0, 20.0, 0.1, 0.5, 500, 150, "porsiya", 1.0,
                           ["high_protein", "high_fat", "high_sodium"],
                           "Sous və qızartma natriumu artırır. Fırında bişmiş variant daha yüngüldür."),
    "chocolate_cake": entry("Şokoladlı tort", 371, 5.0, 50.0, 17.0, 2.0, 36.0, 320, 110, "dilim", 0.9,
                            ["high_sugar", "high_fat"],
                            "Şəkər çox yüksəkdir. Nadir hallarda və kiçik dilimlə yemək məsləhətdir."),
    "chocolate_mousse": entry("Şokoladlı mus", 225, 4.0, 22.0, 14.0, 1.5, 18.0, 60, 100, "porsiya", 0.7,
                              ["high_sugar", "high_fat"],
                              "Kremli desertdir. Qara şokolad variantı bir qədər az şəkərli olur."),
    "churros": entry("Çurro", 356, 4.0, 43.0, 19.0, 1.0, 12.0, 320, 70, "ədəd", 0.6,
                     ["high_sugar", "high_fat"],
                     "Qızardılıб şəkərə bulanır. Şokolad sousu kalorini daha da artırır."),
    "clam_chowder": entry("Midyə şorbası (kremli)", 90, 5.0, 9.0, 4.0, 0.5, 1.5, 400, 300, "kasa", 0.6,
                          ["high_sodium"],
                          "Krem əsaslı olduğu üçün yağlıdır. Duzu yüksəkdir, ölçülü için."),
    "crab_cakes": entry("Yengəc kotleti", 220, 14.0, 10.0, 14.0, 0.5, 1.0, 480, 120, "ədəd", 0.9,
                        ["high_protein", "high_sodium"],
                        "Dəniz məhsulu zülalı verir, amma qızartma və sous natriumu artırır."),
    "creme_brulee": entry("Krem brüle", 300, 4.0, 25.0, 20.0, 0.0, 22.0, 55, 120, "porsiya", 0.9,
                          ["high_sugar", "high_fat"],
                          "Qaymaq və şəkərlə çox kaloridir. Kiçik porsiya seçin."),
    "croque_madame": entry("Krok-madam", 280, 15.0, 20.0, 16.0, 1.0, 3.0, 620, 200, "ədəd", 1.0,
                           ["high_fat", "high_sodium"],
                           "Pendir, vetçina və yumurta ilə yağlı və duzludur. Yanında salat yaxşı gedir."),
    "cup_cakes": entry("Kekslər (cupcake)", 305, 3.5, 45.0, 13.0, 0.8, 33.0, 250, 65, "ədəd", 0.7,
                       ["high_sugar", "high_fat"],
                       "Krem və şəkərdən kalorisi yüksəkdir. Bir ədədlə kifayətlənin."),
    "deviled_eggs": entry("Doldurulmuş yumurta", 190, 10.0, 1.0, 16.0, 0.0, 0.6, 320, 60, "ədəd", 0.9,
                          ["high_protein", "high_fat"],
                          "Zülal mənbəyidir; mayonez yağı artırır. Yunan qatığı ilə daha yüngül olar."),
    "edamame": entry("Edamame (soya paxlası)", 121, 12.0, 9.0, 5.0, 5.2, 2.0, 6, 150, "porsiya", 0.7,
                     ["vegetarian", "high_protein", "high_fiber"],
                     "Bitki zülalı və lifi ilə çox sağlam qəlyanaltıdır. Duz əlavə etməyə ehtiyac yoxdur."),
    "eggs_benedict": entry("Benedikt yumurtası", 240, 12.0, 14.0, 15.0, 0.8, 1.5, 500, 200, "porsiya", 1.0,
                           ["high_fat", "high_sodium", "high_protein"],
                           "Hollandez sousu yağ və kalorini artırır. Zülalla zəngin səhər yeməyidir."),
    "escargots": entry("İlbiz (escargot)", 170, 16.0, 2.0, 11.0, 0.0, 0.0, 380, 100, "porsiya", 1.0,
                       ["high_protein"],
                       "Az karbohidratlı zülal mənbəyidir. Kalorinin çoxu sarımsaqlı kərə yağından gəlir."),
    "filet_mignon": entry("File minyon", 267, 27.0, 0.0, 17.0, 0.0, 0.0, 55, 200, "porsiya", 1.3,
                          ["high_protein", "high_fat"],
                          "Yağsız və zülalla zəngin steykdir. Tərəvəzlə birlikdə balanslı olur."),
    "fish_and_chips": entry("Balıq və kartof (fish and chips)", 230, 12.0, 22.0, 11.0, 1.5, 0.5, 380, 300, "porsiya", 0.9,
                            ["high_carb", "high_fat"],
                            "Xəmir və qızartma kalorini artırır. Fırında bişmiş balıq daha yüngüldür."),
    "foie_gras": entry("Fua-qra (qaz ciyəri)", 462, 11.0, 4.6, 44.0, 0.0, 0.0, 700, 60, "porsiya", 1.0,
                       ["high_fat", "high_sodium"],
                       "Çox yüksək yağ və natrium var. Yalnız kiçik miqdarda dadmaq məsləhətdir."),
    "french_onion_soup": entry("Fransız soğan şorbası", 70, 4.0, 7.0, 3.0, 1.0, 3.0, 450, 300, "kasa", 0.6,
                               ["high_sodium"],
                               "Bulyon və pendirdən duzu yüksəkdir. Çörək qatı kalorini artırır."),
    "french_toast": entry("Fransız tostu", 229, 8.0, 25.0, 11.0, 1.2, 8.0, 350, 130, "ədəd", 0.8,
                          ["high_carb", "high_sugar"],
                          "Sirop əlavə etməzdən əvvəl kalorini nəzərə alın. Meyvə ilə daha balanslıdır."),
    "fried_calamari": entry("Qızardılmış kalmar", 175, 15.0, 8.0, 9.0, 0.3, 0.5, 300, 150, "porsiya", 0.9,
                            ["high_protein", "high_fat"],
                            "Dəniz məhsulu zülalı verir, amma xəmir və qızartma yağı artırır."),
    "frozen_yogurt": entry("Dondurulmuş yoqurt", 127, 3.0, 24.0, 4.0, 0.0, 20.0, 65, 100, "porsiya", 0.7,
                           ["high_sugar"],
                           "Dondurmadan az yağlı ola bilər, amma şəkəri yüksəkdir. Meyvə əlavəsi yaxşıdır."),
    "garlic_bread": entry("Sarımsaqlı çörək", 330, 8.0, 40.0, 15.0, 2.0, 2.5, 550, 80, "dilim", 0.6,
                          ["high_carb", "high_fat", "high_sodium"],
                          "Kərə yağı və çörəkdən kaloridir. Bir-iki dilimlə kifayətlənin."),
    "gnocchi": entry("Nyokki", 130, 4.0, 24.0, 2.0, 1.5, 1.0, 300, 200, "porsiya", 1.0,
                     ["high_carb"],
                     "Kartof əsaslı makarondur. Sous seçimi ümumi kalorini müəyyən edir."),
    "grilled_cheese_sandwich": entry("Pendirli tost", 350, 13.0, 28.0, 20.0, 1.5, 3.0, 640, 120, "ədəd", 0.9,
                                     ["high_fat", "high_sodium"],
                                     "Pendir və kərə yağından yağlıdır. Tam taxıl çörək və pomidor əlavə edin."),
    "gyoza": entry("Gyoza", 210, 8.0, 24.0, 9.0, 1.2, 1.5, 450, 150, "porsiya", 0.9,
                   ["high_carb", "high_sodium"],
                   "Buxarda bişmiş variant qızardılmışdan yüngüldür. Soya sousunu az işlədin."),
    "hot_and_sour_soup": entry("İsti-turş şorba", 55, 4.0, 6.0, 2.0, 0.6, 2.0, 500, 300, "kasa", 0.6,
                               ["high_sodium"],
                               "Kalorisi aşağı, amma duzu yüksəkdir. Yüngül başlanğıc üçün yaxşıdır."),
    "huevos_rancheros": entry("Uevos rançeros", 155, 8.0, 12.0, 9.0, 2.0, 2.0, 400, 250, "porsiya", 0.9,
                              ["high_sodium"],
                              "Yumurta, lobya və tərəvəzlə doyumlu səhər yeməyidir. Sous natriumu artırır."),
    "hummus": entry("Hümus", 166, 8.0, 14.0, 10.0, 6.0, 0.4, 380, 100, "porsiya", 0.8,
                    ["vegetarian", "high_fiber", "healthy_fat"],
                    "Noxud və küncüt pastasından lif və bitki zülalı verir. Tərəvəzlə yaxşı gedir."),
    "lobster_bisque": entry("Omar şorbası (bisque)", 105, 5.0, 8.0, 6.0, 0.3, 2.0, 500, 300, "kasa", 0.6,
                            ["high_sodium"],
                            "Krem əsaslıdır, ona görə yağlı və duzludur. Ölçülü porsiya seçin."),
    "lobster_roll_sandwich": entry("Omarlı sendviç", 240, 12.0, 20.0, 12.0, 1.0, 2.5, 560, 180, "ədəd", 0.9,
                                   ["high_sodium"],
                                   "Mayonez kalorini artırır. Dəniz məhsulu zülal mənbəyidir."),
    "macaroni_and_cheese": entry("Pendirli makaron", 190, 8.0, 20.0, 9.0, 1.0, 3.0, 440, 200, "porsiya", 1.0,
                                 ["high_carb", "high_fat", "high_sodium"],
                                 "Pendir sousundan yağlı və duzludur. Tam taxıl makaron və tərəvəz əlavə edin."),
    "macarons": entry("Makaron (fransız)", 380, 7.0, 55.0, 15.0, 2.0, 48.0, 60, 20, "ədəd", 0.8,
                      ["high_sugar"],
                      "Kiçik olsa da şəkəri çox yüksəkdir. Bir-iki ədədlə kifayətlənin."),
    "miso_soup": entry("Miso şorbası", 40, 3.0, 4.0, 1.5, 0.8, 1.0, 600, 250, "kasa", 0.6,
                       ["high_sodium"],
                       "Kalorisi çox aşağıdır, amma natriumu yüksəkdir. Yüngül başlanğıc üçün yaxşıdır."),
    "mussels": entry("Midyə", 172, 24.0, 7.0, 4.5, 0.0, 0.0, 370, 150, "porsiya", 0.9,
                     ["high_protein"],
                     "Zülal, dəmir və B12 ilə zəngindir. Yağı azdır; təzəliyinə diqqət edin."),
    "nachos": entry("Naços", 310, 8.0, 32.0, 17.0, 3.0, 1.5, 550, 200, "porsiya", 0.6,
                    ["fast_food", "high_fat", "high_sodium"],
                    "Pendir və çipsdən yağlı və duzludur. Bol tərəvəz və lobya əlavə etmək daha yaxşıdır."),
    "onion_rings": entry("Soğan halqaları", 332, 4.5, 38.0, 18.0, 1.8, 4.0, 430, 100, "porsiya", 0.5,
                         ["fast_food", "high_fat", "high_carb"],
                         "Xəmir və qızartmadan kalorisi yüksəkdir. Arabir və kiçik porsiya seçin."),
    "oysters": entry("İstridyə", 81, 9.0, 5.0, 2.3, 0.0, 0.0, 210, 100, "porsiya", 0.9,
                     ["high_protein"],
                     "Az kalorili, sink və dəmirlə zəngindir. Təzəliyi çox vacibdir."),
    "pad_thai": entry("Pad-tay", 150, 7.0, 20.0, 5.0, 1.5, 5.0, 470, 300, "boşqab", 0.9,
                      ["high_carb", "high_sodium"],
                      "Düyü əriştəsi əsaslıdır; sous şəkər və duz əlavə edir. Zülal və tərəvəzlə balanslaşdırın."),
    "paella": entry("Paelya", 160, 9.0, 20.0, 5.0, 1.0, 1.5, 420, 300, "boşqab", 0.9,
                    ["high_carb", "high_sodium"],
                    "Düyü, dəniz məhsulu və ətlə doyumlu yeməkdir. Porsiya ölçüsünə diqqət edin."),
    "panna_cotta": entry("Panna-kotta", 240, 3.5, 22.0, 15.0, 0.0, 20.0, 45, 110, "porsiya", 0.9,
                         ["high_sugar", "high_fat"],
                         "Qaymaq əsaslı desertdir. Meyvə sousu ilə şəkəri təbii şəkildə balanslaşdırın."),
    "peking_duck": entry("Pekin ördəyi", 240, 19.0, 4.0, 17.0, 0.2, 2.0, 400, 150, "porsiya", 1.0,
                         ["high_protein", "high_fat"],
                         "Dərisi yağlıdır. Zülal mənbəyidir, dərisiz hissə daha yüngüldür."),
    "pho": entry("Fo (Vyetnam şorbası)", 70, 6.0, 9.0, 1.5, 0.5, 1.0, 400, 500, "kasa", 0.6,
                 ["high_sodium"],
                 "Bulyonun duzu yüksəkdir. Bol tərəvəz və zülalla doyumlu, aşağı kalorili seçimdir."),
    "pork_chop": entry("Donuz kotleti", 231, 26.0, 0.0, 14.0, 0.0, 0.0, 60, 200, "porsiya", 1.2,
                       ["high_protein", "high_fat"],
                       "Zülalla zəngindir. Yağsız hissəni seçib tərəvəzlə yemək məsləhətdir."),
    "poutine": entry("Putin (kartof-pendir)", 230, 6.0, 24.0, 12.0, 2.0, 1.0, 500, 300, "porsiya", 0.9,
                     ["fast_food", "high_fat", "high_sodium"],
                     "Kartof, pendir və sousdan çox kaloridir. Arabir və kiçik porsiya seçin."),
    "prime_rib": entry("Prime rib (mal əti)", 290, 25.0, 0.0, 21.0, 0.0, 0.0, 55, 250, "porsiya", 1.3,
                       ["high_protein", "high_fat"],
                       "Zülalla zəngin, amma yağlı ət kəsimidir. Porsiyanı ölçülü saxlayın."),
    "pulled_pork_sandwich": entry("Donuz ətli sendviç", 250, 15.0, 24.0, 10.0, 1.2, 8.0, 560, 220, "ədəd", 1.0,
                                  ["high_sodium"],
                                  "Barbekü sousu şəkər və natriumu artırır. Yanında salatla balanslaşdırın."),
    "ravioli": entry("Ravioli", 160, 7.0, 22.0, 5.0, 1.5, 2.0, 350, 220, "porsiya", 1.0,
                     ["high_carb"],
                     "Doldurmadan asılı olaraq kalori dəyişir. Pomidor sousu kremliyə nisbətən yüngüldür."),
    "red_velvet_cake": entry("Qırmızı məxmər tortu", 370, 4.0, 50.0, 18.0, 1.0, 38.0, 300, 110, "dilim", 0.9,
                             ["high_sugar", "high_fat"],
                             "Krem-pendir qlazuru ilə şəkəri çox yüksəkdir. Kiçik dilim seçin."),
    "risotto": entry("Rizotto", 170, 4.0, 24.0, 6.0, 0.8, 1.0, 360, 250, "porsiya", 1.0,
                     ["high_carb"],
                     "Kərə yağı və pendir kalorini artırır. Göbələk və tərəvəzli variant daha yüngüldür."),
    "samosa": entry("Samosa", 262, 5.0, 30.0, 13.0, 2.5, 2.0, 420, 100, "ədəd", 0.8,
                    ["vegetarian", "high_carb", "high_fat"],
                    "Qızardılmış xəmir yağı artırır. Fırında bişmiş variant daha sağlamdır."),
    "sashimi": entry("Saşimi", 130, 22.0, 0.5, 4.0, 0.0, 0.0, 60, 120, "porsiya", 1.0,
                     ["high_protein"],
                     "Çiy balıqdır; zülal və omeqa-3 verir, karbohidratı yoxdur. Təzəliyi vacibdir."),
    "scallops": entry("Taraq (scallop)", 111, 20.0, 5.0, 0.8, 0.0, 0.0, 570, 120, "porsiya", 0.9,
                      ["high_protein", "high_sodium"],
                      "Az yağlı, yüksək zülallı dəniz məhsuludur. Duzu təbii olaraq yüksəkdir."),
    "seaweed_salad": entry("Dəniz yosunu salatı", 70, 1.5, 9.0, 3.5, 1.5, 1.0, 400, 100, "porsiya", 0.7,
                           ["healthy_fat", "high_sodium"],
                           "Yod və mineral mənbəyidir. Sousdan duzu yüksək ola bilər."),
    "shrimp_and_grits": entry("Karides və qarğıdalı sıyığı", 150, 9.0, 15.0, 6.0, 0.8, 0.5, 420, 250, "porsiya", 0.9,
                              ["high_sodium"],
                              "Karides zülal verir; kərə yağı və pendir kalorini artırır."),
    "spaghetti_carbonara": entry("Karbonara spagetti", 190, 8.0, 22.0, 8.0, 1.2, 1.5, 400, 300, "boşqab", 0.9,
                                 ["high_carb", "high_fat"],
                                 "Yumurta, pendir və bekondan yağlıdır. Porsiyanı ölçülü saxlayın."),
    "spring_rolls": entry("Bahar rulonu", 150, 4.0, 20.0, 6.0, 1.5, 3.0, 380, 100, "ədəd", 0.8,
                          ["high_carb"],
                          "Təzə (bişməmiş) variant qızardılmışdan daha yüngüldür. Tərəvəzlə doludur."),
    "strawberry_shortcake": entry("Çiyələkli tort", 290, 4.0, 42.0, 12.0, 1.5, 28.0, 250, 120, "dilim", 0.8,
                                  ["high_sugar"],
                                  "Çiyələk vitamin verir, amma qaymaq və şəkər kalorini artırır."),
    "takoyaki": entry("Takoyaki", 190, 7.0, 22.0, 8.0, 0.8, 2.0, 450, 150, "porsiya", 0.9,
                      ["high_carb", "high_sodium"],
                      "Xəmir və sousdan karbohidrat və duzu yüksəkdir. Ölçülü porsiya seçin."),
    "tiramisu": entry("Tiramisu", 283, 5.0, 30.0, 16.0, 0.6, 22.0, 90, 110, "dilim", 0.9,
                      ["high_sugar", "high_fat"],
                      "Maskarpone və şəkərlə kaloridir. Kiçik dilimlə kifayətlənin."),
    "tuna_tartare": entry("Ton balığı tartarı", 150, 22.0, 2.0, 6.0, 0.3, 0.5, 350, 130, "porsiya", 0.9,
                          ["high_protein"],
                          "Çiy ton zülal və omeqa-3 verir. Təzəlik və gigiyena vacibdir."),
}


def main() -> None:
    missing = [c for c in CLASSES if c not in DB]
    extra = [c for c in DB if c not in CLASSES]
    if missing or extra:
        raise ValueError(f"DB mismatch: missing={missing}, extra={extra}")
    out = settings.nutrition_db_path
    with out.open("w", encoding="utf-8") as f:
        json.dump(DB, f, ensure_ascii=False, indent=2)
    print(f"Wrote {out} with {len(DB)} entries")


if __name__ == "__main__":
    main()
